[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "nhl_model"
authors = [
	{name = "Brent Barbachem", email = "barbacbd@gmail.com"},
]
description = "Package to create a model that can be used to predict the result of NHL games."
license = {text = "MIT"}
readme = "README.md"
requires-python = ">=3.8,<3.13"
keywords = [
    "python",
    "machine-learning",
    "statistics",
    "sports",
    "prediction",
    "python3",
    "pytorch",
    "predictive-modeling",
    "nhl-core",
    "sports-stats",
    "sports-analytics",
    "event-analysis"
]
classifiers = [
    "Intended Audience :: Science/Research",
    "License :: Freeware",
    "Natural Language :: English",
    "Operating System :: MacOS :: MacOS X",
    "Operating System :: POSIX :: Linux",
    "Operating System :: Microsoft :: Windows",
    "Programming Language :: Python :: 3",
    "Topic :: Software Development"
]
dependencies = [
    "inquirer>=3.0,<4.0",
    "scipy>=1.10,<2.0",
    "keras>=2.13,<3.0",
    "tensorflow>=2.13,<3.0",
    "numpy>=1.24,<2.0",
    "pandas>=2.0,<3.0",
    "openpyxl>=3.0,<4.0",
    "mrmr_selection>=0.2.0,<1.0",
    "nhl-core>=1.0,<2.0",
    "requests>=2.28,<3.0",
]
dynamic = ["version"]

[tool.setuptools]
include-package-data = true

[project.optional-dependencies]
tests = [
    "pytest",
    "coverage",
    "pytest-cov",
    "mock",
    "pylint",
    "pytest-order",
    "pytest-subtests",
]
lint = [
    "pylint",  # this exists in multiple spaces, and that's ok
]
clean = [
    "pyclean",
]
dev = [
    "pre-commit>=3.5.0",
    "black>=24.0.0",
    "isort>=5.13.0",
    "bandit[toml]>=1.7.0",
]
[project.scripts]
nhl-predict = "nhl_model.exec:main"

[tool.setuptools.package-data]
'src' = [
    'nhl_model/support/schedules/2022/*.json',
    'nhl_model/support/NHLTeams.json',
]
