name: Pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .[lint]
    - name: Analyze the source code with pylint
      run: |
        pylint src/nhl_model/ --rcfile .pylintrc
    - name: Analyze the test code with pylint
      run: |
        pylint tests/ --rcfile .pylintrc
