# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ main ]
  pull_request:
    types:
      - opened
      - edited

jobs:
  systems-tests:
    runs-on: ${{ matrix.os }}
    name: ${{matrix.os}}-${{matrix.python-version}}
    strategy:
      max-parallel: 1
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.10"]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Local install
        run: |
          python -m pip install .
      - name: Setup Git
        run: |
          git config --global user.name "Brent Barbachem"
          git config --global user.email "barbacbd@dukes.jmu.edu"
      - name: Install Test Deps
        run: |
          python -m pip install -e .[tests]
          python -m pip install coverage-badge
      - name: Tests
        env:
          token: ${{ secrets.CI_TOKEN }}
        run: |
          pytest --cov=tests
          mv .coverage .cov/
          pushd .cov
          rm -rf coverage-badge.svg
          coverage-badge -o coverage-badge.svg
          popd
          git ls-files --modified | xargs git add
          git commit -m "[Automated Commit]: Adding code coverage information from unit tests." || echo "no changes to commit"
          git remote set-url --push origin https://barbacbd:$token@github.com/barbacbd/NHLModel || echo "no need to set remote"
          git push --force || echo "nothing to push"
